;***********************************************************************
;
;   イニシャルファイル
;
;   Create Date : 2025/05/10 hoi      Ver1.00
;   Update Date :
;
;***********************************************************************

;-----------------------------------------------------------------------
;
;   対ＰＬＣ通信設定
;       NETWORK     : ＰＬＣ側ネットワーク番号
;       NO          : ＰＬＣ側ＰＣ番号
;       PLC-ADDR1   : ＰＬＣ側ＩＰアドレス(１桁目)
;       PLC-ADDR2   : ＰＬＣ側ＩＰアドレス(２桁目)
;       PLC-ADDR3   : ＰＬＣ側ＩＰアドレス(３桁目)
;       PLC-ADDR4   : ＰＬＣ側ＩＰアドレス(４桁目)
;       PLC-PORT    : ＰＬＣ側ポート番号
;
;-----------------------------------------------------------------------
[PLC]
 NETWORK    = 0
 NO         = 255
 IP-ADDR    = 192.168.3.100
 PORT       = 4096

;-----------------------------------------------------------------------
;
;   エクセルファイルのパス
;       SHT_DENMAST     : 項目マスター
;       SHT_DENPRT      : 車種登録情報フォーム
;
;-----------------------------------------------------------------------
[PATH]
 SHT_DENMAST    = "D:\X61GX42H1ST\MtFiles\項目マスター.xls"
 SHT_DENPRT     = "D:\X61GX42H1ST\MtFiles\車種登録情報フォーム.xls"

;-----------------------------------------------------------------------
;
;   メインウィンドウ表示オフセット
;       X           : 表示位置Ｘ
;       Y           : 表示位置Ｙ
;       WIDTH       : 表示幅
;       HEIGHT      : 表示高さ
;
;-----------------------------------------------------------------------
[SCREEN]
 X          = -6
 Y          = 0
 WIDTH      = 0
 HEIGHT     = 0
